<a href="https://colab.research.google.com/github/DinalAdithya/Learning-PYTorch/blob/main/Pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print (torch.__version__)

2.1.0+cu118


Intoduction to Tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# no dimantions
scalar.ndim

0

In [4]:
# get tensor back as Python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX =torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[0][1]

tensor([4, 5, 6])

In [18]:
TENSOR[0][1][2]

tensor(6)

### Random TENSORS

1. These are importent becouse the way many neural networks learn with random Tensors.

2. Then adjust those random Tensors to better represnt data.

In [19]:
# Create a random Tensors of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6136, 0.8299, 0.9842, 0.1707],
        [0.7514, 0.6825, 0.2512, 0.3490],
        [0.0232, 0.6497, 0.5610, 0.9171]])

In [20]:
random_tensor.ndim

2

In [21]:
# Create random tensor with similar shape to an image tensor
ramdom_image_size_tensor = torch.rand(size= (3, 244, 244))
ramdom_image_size_tensor.shape, ramdom_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and ones


In [22]:
# Creaate tensor with all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

###Creating Range of Tensors and tensors like



In [26]:
# use torch. range()[range dose not support so arange()]
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
torch.arange(start = 1, end = 11)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
torch.arange(1,1000,77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [29]:
torch.arange(start = 1, end = 1000, step = 77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [30]:
# create tensors like (use this if need to create a tensor likes
# something else  ) it just copy the shape

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data type
***NOTE: 3 big errors

      1. Tensors not right dtypr
      2. Tensors not right shape
      3. Tensors not on the right device  


In [32]:
# defult comes with float 32
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None)
tensor_type

tensor([3., 6., 9.])

In [33]:
tensor_type.dtype

torch.float32

In [35]:
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=torch.float16)
tensor_type.dtype

torch.float16

In [37]:
# importent parameters to be aware of
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None,# what data type is the tensor
                           device=None,# what devise is you tensor on
                           requires_grad=False)# whether or not track gradiants this tensors operations
tensor_type

tensor([3., 6., 9.])

In [41]:
float_16_tensor = tensor_type.type(torch.half) # or u can use (torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)