<a href="https://colab.research.google.com/github/DinalAdithya/Learning-PYTorch/blob/main/Pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print (torch.__version__)

2.1.0+cu121


Intoduction to Tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# no dimantions
scalar.ndim

0

In [4]:
# get tensor back as Python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX =torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[0][1]

tensor([4, 5, 6])

In [18]:
TENSOR[0][1][2]

tensor(6)

### Random TENSORS

1. These are importent becouse the way many neural networks learn with random Tensors.

2. Then adjust those random Tensors to better represnt data.

In [19]:
# Create a random Tensors of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5744, 0.8617, 0.8935, 0.1222],
        [0.7789, 0.2655, 0.9114, 0.8209],
        [0.1043, 0.6240, 0.8324, 0.0079]])

In [20]:
random_tensor.ndim

2

In [21]:
# Create random tensor with similar shape to an image tensor
ramdom_image_size_tensor = torch.rand(size= (3, 244, 244))
ramdom_image_size_tensor.shape, ramdom_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and ones


In [22]:
# Creaate tensor with all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

###Creating Range of Tensors and tensors like



In [26]:
# use torch. range()[range dose not support so arange()]
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
torch.arange(start = 1, end = 11)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
torch.arange(1,1000,77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [29]:
torch.arange(start = 1, end = 1000, step = 77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [30]:
# create tensors like (use this if need to create a tensor likes
# something else  ) it just copy the shape

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data type
***NOTE: 3 big errors

      1. Tensors not right dtypr
      2. Tensors not right shape
      3. Tensors not on the right device  


In [32]:
# defult comes with float 32
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None)
tensor_type

tensor([3., 6., 9.])

In [33]:
tensor_type.dtype

torch.float32

In [34]:
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=torch.float16)
tensor_type.dtype

torch.float16

In [35]:
# importent parameters to be aware of
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None,# what data type is the tensor
                           device=None,# what devise is you tensor on
                           requires_grad=False)# whether or not track gradiants this tensors operations
tensor_type

tensor([3., 6., 9.])

In [36]:
float_16_tensor = tensor_type.type(torch.half) # or u can use (torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
# even though we could multyply 2 tensors of defferent dtype here
# it not work on every places so be care full

float_16_tensor * tensor_type

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [39]:
int_32_tensor *  float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [40]:
int_32_tensor *  tensor_type

tensor([ 9., 36., 81.])

### Getting informations from tensors

1. Tensors not right dtypr     - tensor.dtype
2. Tensors not right shape         - tensor.shape
3. Tensors not on the right device - tensor.device

In [41]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1617, 0.6963, 0.1458, 0.6899],
        [0.0210, 0.9064, 0.3658, 0.4874],
        [0.0295, 0.0164, 0.5488, 0.4385]])

In [42]:
# Find out details about tensors

print(some_tensor, "\n")
print(f"Datatype of tensor : {some_tensor.dtype}\n")

# these two are same acsept one is a attribute other one is def(function)
print(f"Shape of a tensor : {some_tensor.shape}")
print(f"Shape of a tensor : {some_tensor.size()}\n")

# all the tensor that we create is on cpu as defult
print(f"Device tensor is on : {some_tensor.device}")



tensor([[0.1617, 0.6963, 0.1458, 0.6899],
        [0.0210, 0.9064, 0.3658, 0.4874],
        [0.0295, 0.0164, 0.5488, 0.4385]]) 

Datatype of tensor : torch.float32

Shape of a tensor : torch.Size([3, 4])
Shape of a tensor : torch.Size([3, 4])

Device tensor is on : cpu


### Manipulating Tensors (tensor operations)


  

1.   Addition
2.   Subtraction
3.   Multiplication (elemnt-wise)
4.   Division
5.   Matrix multiplication




In [43]:
# create a tensor & add 10 to it
gg = torch.tensor([1, 2, 3])

gg + 10

tensor([11, 12, 13])

In [44]:
# PYTorch  in build function
gg.add(100)

tensor([101, 102, 103])

In [45]:
# multiply tensor by 10
gg * 10


tensor([10, 20, 30])

In [46]:
# Substract
gg - 10

tensor([-9, -8, -7])

In [47]:
### matrix multiplication [2 types]
  # 1. Element-wise Multiplication
  # 2. matrix multiplication [dot products]

In [48]:
# 1. Element-wise Multiplication
print(gg, "*", gg)
print(f"Equals:, {gg * gg}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:, tensor([1, 4, 9])


In [49]:
# 2. matrix multiplication
%%time
torch.matmul(gg ,gg) # insted of matmul we can use mm [sorter virsion]

CPU times: user 278 µs, sys: 52 µs, total: 330 µs
Wall time: 4.65 ms


tensor(14)

In [50]:
## or we can use @ to do the aboue same thing
%%time
gg @ gg
# time is way low for using @

CPU times: user 116 µs, sys: 0 ns, total: 116 µs
Wall time: 120 µs


tensor(14)

In [51]:
#by hand = 1*1 + 2*2 + 3*3

In [52]:
%%time
value = 0
for i in range(len(gg)):
  value += gg[i] * gg[i]
print(value)

tensor(14)
CPU times: user 1.79 ms, sys: 0 ns, total: 1.79 ms
Wall time: 2.67 ms


###                          **  Fun fact **
If we didnt print the [ print(value)] = 1.41ms


and use just value it take more time           = 6ms


same reason why c++ faster for gaming than python

In [53]:
### One of the most common error = shap error

**1 . Inner dimentions must match**

*   (3, 2)  @  (3, 2) = Won't work
*   (2, 3)  @  (3, 2) = Will work
*   (3, 2)  @  (2, 3) = Will work

**2. The resulting matrix has the shape of the outer dimention**


1.   (2, 3)  @  (3, 2) -> (2, 2)
2.   (3, 2)  @  (2, 3) -> (3, 3)






## Error
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))


In [55]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6411, 0.4619],
        [0.9955, 0.4817]])

In [56]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[1.0471, 0.8456, 0.6525],
        [0.5419, 0.3196, 0.3289],
        [1.1083, 0.7747, 0.6817]])

In [61]:
## Error
# shapes for metrix multiplication
tensor_A =  torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

## Error
torch.mm(tensor_A , tensor_B)

In [58]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix shape issues, we can use **transpose**

In [62]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [63]:
tensor_B.T, tensor_B.T.shape ## now the shapes of thensor b is changed

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [64]:
# now you dont get an error [becouse tensor_B is transpose now]
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes:      tensor_A = {tensor_A.shape}(same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplaing:                {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimention must match")
print("\noutput :")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes:      tensor_A = torch.Size([3, 2])(same as above), tensor_B.T = torch.Size([2, 3])
Multiplaing:                torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimention must match

output :
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Tensor Aggregation
#### Finding the min, mean, sum etc

In [74]:
# Create a Tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [66]:
# To Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [67]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [70]:
## Mean [ x.mean() dose not work ]  / torch.mean(x)
### becouse torch mean fun dose not work for dtype int64

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [71]:
# Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the Positional mid and max

In [76]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [75]:
x.argmin() # return the index of the min value

tensor(0)

In [77]:
x.argmax() # return the index of the max value

tensor(9)

#Reshaping, stacking, squeezing, and unsqueezing tensor
* reshaping - reshape an input tensor to a difine shape
* view - return view of an input tensor of certain shape but keep the same memory
* squeezing - removes all '1' dimensions from a tensor
* unsqueezing - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [89]:
# let's create a tensor
import torch # note book can run the sell derectly from here
x = torch.arange(1., 11.)
x, x.shape, x.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 torch.float32)

In [98]:
# Reshape = add extra dimention
x_reshape = x.reshape(2, 5) # this workd becouse 5*2= 10 [x has 10 element] any combinations oky
x_reshape, x_reshape.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [99]:
# View = Change the view
z =  x.view(1, 10)
z, z.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [100]:
# changing z changes x
# because a view of a tensor shares the same memory as original input

z[ :, 0] = 5 # need to have a space before :
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [101]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0 ) # difoult dimention also 0
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [102]:
x_stacked = torch.stack([x, x, x, x], dim = 1 ) # can't have more than 1 dimention for this
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])