<a href="https://colab.research.google.com/github/DinalAdithya/Learning-PYTorch/blob/main/Pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print (torch.__version__)

2.1.0+cu121


Intoduction to Tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# no dimantions
scalar.ndim

0

In [4]:
# get tensor back as Python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX =torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[0][1]

tensor([4, 5, 6])

In [18]:
TENSOR[0][1][2]

tensor(6)

### Random TENSORS

1. These are importent becouse the way many neural networks learn with random Tensors.

2. Then adjust those random Tensors to better represnt data.

In [19]:
# Create a random Tensors of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0045, 0.4809, 0.0541, 0.6225],
        [0.5757, 0.8809, 0.2061, 0.7594],
        [0.2274, 0.2735, 0.5649, 0.3291]])

In [20]:
random_tensor.ndim

2

In [21]:
# Create random tensor with similar shape to an image tensor
ramdom_image_size_tensor = torch.rand(size= (3, 244, 244))
ramdom_image_size_tensor.shape, ramdom_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and ones


In [22]:
# Creaate tensor with all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

###Creating Range of Tensors and tensors like



In [26]:
# use torch. range()[range dose not support so arange()]
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
torch.arange(start = 1, end = 11)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
torch.arange(1,1000,77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [29]:
torch.arange(start = 1, end = 1000, step = 77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [30]:
# create tensors like (use this if need to create a tensor likes
# something else  ) it just copy the shape

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data type
***NOTE: 3 big errors

      1. Tensors not right dtypr
      2. Tensors not right shape
      3. Tensors not on the right device  


In [32]:
# defult comes with float 32
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None)
tensor_type

tensor([3., 6., 9.])

In [33]:
tensor_type.dtype

torch.float32

In [34]:
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=torch.float16)
tensor_type.dtype

torch.float16

In [35]:
# importent parameters to be aware of
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None,# what data type is the tensor
                           device=None,# what devise is you tensor on
                           requires_grad=False)# whether or not track gradiants this tensors operations
tensor_type

tensor([3., 6., 9.])

In [36]:
float_16_tensor = tensor_type.type(torch.half) # or u can use (torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
# even though we could multyply 2 tensors of defferent dtype here
# it not work on every places so be care full

float_16_tensor * tensor_type

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [39]:
int_32_tensor *  float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [40]:
int_32_tensor *  tensor_type

tensor([ 9., 36., 81.])

### Getting informations from tensors

1. Tensors not right dtypr     - tensor.dtype
2. Tensors not right shape         - tensor.shape
3. Tensors not on the right device - tensor.device

In [41]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4190, 0.4190, 0.3188, 0.3161],
        [0.7913, 0.8701, 0.9412, 0.8683],
        [0.0182, 0.1492, 0.6427, 0.8605]])

In [42]:
# Find out details about tensors

print(some_tensor, "\n")
print(f"Datatype of tensor : {some_tensor.dtype}\n")

# these two are same acsept one is a attribute other one is def(function)
print(f"Shape of a tensor : {some_tensor.shape}")
print(f"Shape of a tensor : {some_tensor.size()}\n")

# all the tensor that we create is on cpu as defult
print(f"Device tensor is on : {some_tensor.device}")



tensor([[0.4190, 0.4190, 0.3188, 0.3161],
        [0.7913, 0.8701, 0.9412, 0.8683],
        [0.0182, 0.1492, 0.6427, 0.8605]]) 

Datatype of tensor : torch.float32

Shape of a tensor : torch.Size([3, 4])
Shape of a tensor : torch.Size([3, 4])

Device tensor is on : cpu


### Manipulating Tensors (tensor operations)


  

1.   Addition
2.   Subtraction
3.   Multiplication (elemnt-wise)
4.   Division
5.   Matrix multiplication




In [43]:
# create a tensor & add 10 to it
gg = torch.tensor([1, 2, 3])

gg + 10

tensor([11, 12, 13])

In [44]:
# PYTorch  in build function
gg.add(100)

tensor([101, 102, 103])

In [45]:
# multiply tensor by 10
gg * 10


tensor([10, 20, 30])

In [46]:
# Substract
gg - 10

tensor([-9, -8, -7])

In [47]:
### matrix multiplication [2 types]
  # 1. Element-wise Multiplication
  # 2. matrix multiplication [dot products]

In [51]:
# 1. Element-wise Multiplication
print(gg, "*", gg)
print(f"Equals:, {gg * gg}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:, tensor([1, 4, 9])


In [63]:
# 2. matrix multiplication
%%time
torch.matmul(gg ,gg)

CPU times: user 746 µs, sys: 0 ns, total: 746 µs
Wall time: 708 µs


tensor(14)

In [53]:
#by hand = 1*1 + 2*2 + 3*3

In [77]:
%%time
value = 0
for i in range(len(gg)):
  value += gg[i] * gg[i]
print(value)

tensor(14)
CPU times: user 1.56 ms, sys: 0 ns, total: 1.56 ms
Wall time: 1.41 ms


###                          **  Fun fact **
If we didnt print the [ print(value)] = 1.41ms


and use just value it take more time           = 6ms


same reason why c++ faster for gaming than python

In [79]:
### One of the most common error = shap error