<a href="https://colab.research.google.com/github/DinalAdithya/Learning-PYTorch/blob/main/Pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print (torch.__version__)

2.1.0+cu121


Intoduction to Tensors

In [119]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [120]:
# no dimantions
scalar.ndim

0

In [121]:
# get tensor back as Python int
scalar.item()

7

In [122]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [123]:
vector.ndim

1

In [124]:
vector.shape

torch.Size([2])

In [125]:
# MATRIX
MATRIX =torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [126]:
MATRIX.ndim

2

In [127]:
MATRIX[0]

tensor([7, 8])

In [128]:
MATRIX[1]

tensor([ 9, 10])

In [129]:
MATRIX.shape

torch.Size([2, 2])

In [130]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [131]:
TENSOR.ndim

3

In [132]:
TENSOR.shape

torch.Size([2, 3, 3])

In [133]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [134]:
TENSOR[0][1]

tensor([4, 5, 6])

In [135]:
TENSOR[0][1][2]

tensor(6)

### Random TENSORS

1. These are importent becouse the way many neural networks learn with random Tensors.

2. Then adjust those random Tensors to better represnt data.

In [136]:
# Create a random Tensors of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [137]:
random_tensor.ndim

2

In [138]:
# Create random tensor with similar shape to an image tensor
ramdom_image_size_tensor = torch.rand(size= (3, 244, 244))
ramdom_image_size_tensor.shape, ramdom_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and ones


In [139]:
# Creaate tensor with all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [140]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [141]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [142]:
ones.dtype

torch.float32

###Creating Range of Tensors and tensors like



In [143]:
# use torch. range()[range dose not support so arange()]
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
torch.arange(start = 1, end = 11)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
torch.arange(1,1000,77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [146]:
torch.arange(start = 1, end = 1000, step = 77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [147]:
# create tensors like (use this if need to create a tensor likes
# something else  ) it just copy the shape

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data type
***NOTE: 3 big errors

      1. Tensors not right dtypr
      2. Tensors not right shape
      3. Tensors not on the right device  


In [149]:
# defult comes with float 32
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None)
tensor_type

tensor([3., 6., 9.])

In [150]:
tensor_type.dtype

torch.float32

In [151]:
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=torch.float16)
tensor_type.dtype

torch.float16

In [152]:
# importent parameters to be aware of
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None,# what data type is the tensor
                           device=None,# what devise is you tensor on
                           requires_grad=False)# whether or not track gradiants this tensors operations
tensor_type

tensor([3., 6., 9.])

In [153]:
float_16_tensor = tensor_type.type(torch.half) # or u can use (torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [154]:
# even though we could multyply 2 tensors of defferent dtype here
# it not work on every places so be care full

float_16_tensor * tensor_type

tensor([ 9., 36., 81.])

In [155]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [156]:
int_32_tensor *  float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [157]:
int_32_tensor *  tensor_type

tensor([ 9., 36., 81.])

### Getting informations from tensors

1. Tensors not right dtypr     - tensor.dtype
2. Tensors not right shape         - tensor.shape
3. Tensors not on the right device - tensor.device

In [158]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2549, 0.8068, 0.2459, 0.4506],
        [0.5305, 0.5993, 0.4955, 0.1359],
        [0.5243, 0.5060, 0.9585, 0.6795]])

In [159]:
# Find out details about tensors

print(some_tensor, "\n")
print(f"Datatype of tensor : {some_tensor.dtype}\n")

# these two are same acsept one is a attribute other one is def(function)
print(f"Shape of a tensor : {some_tensor.shape}")
print(f"Shape of a tensor : {some_tensor.size()}\n")

# all the tensor that we create is on cpu as defult
print(f"Device tensor is on : {some_tensor.device}")



tensor([[0.2549, 0.8068, 0.2459, 0.4506],
        [0.5305, 0.5993, 0.4955, 0.1359],
        [0.5243, 0.5060, 0.9585, 0.6795]]) 

Datatype of tensor : torch.float32

Shape of a tensor : torch.Size([3, 4])
Shape of a tensor : torch.Size([3, 4])

Device tensor is on : cpu


### Manipulating Tensors (tensor operations)


  

1.   Addition
2.   Subtraction
3.   Multiplication (elemnt-wise)
4.   Division
5.   Matrix multiplication




In [160]:
# create a tensor & add 10 to it
gg = torch.tensor([1, 2, 3])

gg + 10

tensor([11, 12, 13])

In [161]:
# PYTorch  in build function
gg.add(100)

tensor([101, 102, 103])

In [162]:
# multiply tensor by 10
gg * 10


tensor([10, 20, 30])

In [163]:
# Substract
gg - 10

tensor([-9, -8, -7])

In [164]:
### matrix multiplication [2 types]
  # 1. Element-wise Multiplication
  # 2. matrix multiplication [dot products]

In [165]:
# 1. Element-wise Multiplication
print(gg, "*", gg)
print(f"Equals:, {gg * gg}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:, tensor([1, 4, 9])


In [166]:
# 2. matrix multiplication
%%time
torch.matmul(gg ,gg) # insted of matmul we can use mm [sorter virsion]

CPU times: user 42 µs, sys: 0 ns, total: 42 µs
Wall time: 45.3 µs


tensor(14)

In [167]:
## or we can use @ to do the aboue same thing
%%time
gg @ gg
# time is way low for using @

CPU times: user 40 µs, sys: 0 ns, total: 40 µs
Wall time: 43.6 µs


tensor(14)

In [168]:
#by hand = 1*1 + 2*2 + 3*3

In [169]:
%%time
value = 0
for i in range(len(gg)):
  value += gg[i] * gg[i]
print(value)

tensor(14)
CPU times: user 479 µs, sys: 0 ns, total: 479 µs
Wall time: 485 µs


###                          **  Fun fact **
If we didnt print the [ print(value)] = 1.41ms


and use just value it take more time           = 6ms


same reason why c++ faster for gaming than python

In [170]:
### One of the most common error = shap error

**1 . Inner dimentions must match**

*   (3, 2)  @  (3, 2) = Won't work
*   (2, 3)  @  (3, 2) = Will work
*   (3, 2)  @  (2, 3) = Will work

**2. The resulting matrix has the shape of the outer dimention**


1.   (2, 3)  @  (3, 2) -> (2, 2)
2.   (3, 2)  @  (2, 3) -> (3, 3)






## Error
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))


In [171]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6496, 0.4272],
        [0.7124, 0.3551]])

In [172]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.8481, 0.5238, 1.0118],
        [0.8570, 0.5574, 1.0072],
        [0.8634, 0.4355, 1.0825]])

In [173]:
## Error
# shapes for metrix multiplication
tensor_A =  torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

## Error
torch.mm(tensor_A , tensor_B)

In [174]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix shape issues, we can use **transpose**

In [175]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [176]:
tensor_B.T, tensor_B.T.shape ## now the shapes of thensor b is changed

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [177]:
# now you dont get an error [becouse tensor_B is transpose now]
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes:      tensor_A = {tensor_A.shape}(same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplaing:                {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimention must match")
print("\noutput :")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes:      tensor_A = torch.Size([3, 2])(same as above), tensor_B.T = torch.Size([2, 3])
Multiplaing:                torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimention must match

output :
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Tensor Aggregation
#### Finding the min, mean, sum etc

In [178]:
# Create a Tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [179]:
# To Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [180]:
# Max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [181]:
## Mean [ x.mean() dose not work ]  / torch.mean(x)
### becouse torch mean fun dose not work for dtype int64

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [182]:
# Sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

# Finding the Positional mid and max

In [183]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [184]:
x.argmin() # return the index of the min value

tensor(0)

In [185]:
x.argmax() # return the index of the max value

tensor(9)

#Reshaping, stacking, squeezing, and unsqueezing tensor
* reshaping - reshape an input tensor to a difine shape
* view - return view of an input tensor of certain shape but keep the same memory
* squeezing - removes all '1' dimensions from a tensor
* unsqueezing - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [186]:
# let's create a tensor
import torch # note book can run the sell derectly from here
x = torch.arange(1., 11.)
x, x.shape, x.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 torch.float32)

In [187]:
# Reshape = add extra dimention
x_reshape = x.reshape(2, 5) # this workd becouse 5*2= 10 [x has 10 element] any combinations oky
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [188]:
# View = Change the view
z =  x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [189]:
# changing z changes x
# because a view of a tensor shares the same memory as original input

z[ :, 0] = 5 # need to have a space before :
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [190]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0 ) # difoult dimention also 0
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [191]:
x_stacked = torch.stack([x, x, x, x], dim = 1 ) # can't have more than 1 dimention for this
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [192]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped = torch.rand(1, 9)
print(f"Tensor : {x_reshaped}")
print(f"Tensor Shape : {x_reshaped.shape}")

# removing extra dimentions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor : {x_squeezed}")
print(f"New Tensor Shape : {x_squeezed.shape}")


Tensor : tensor([[0.2916, 0.1722, 0.9716, 0.7282, 0.4054, 0.7865, 0.9859, 0.6173, 0.5845]])
Tensor Shape : torch.Size([1, 9])

New Tensor : tensor([0.2916, 0.1722, 0.9716, 0.7282, 0.4054, 0.7865, 0.9859, 0.6173, 0.5845])
New Tensor Shape : torch.Size([9])


In [193]:
# Torch.unsqueezed() - adds a single dimension to a target tensor at a specific dim
print(f"Previous Target : {x_squeezed}")
print(f"Previous Shape : {x_squeezed.shape}")

# Add an extra dim with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim =  0)
print(f"\nNew Tensor : {x_unsqueezed}")
print(f"New Tensor Shape : {x_unsqueezed.shape}")


# dim 1
x_unsqueezed = x_squeezed.unsqueeze(dim =  1)
print(f"\nNew Tensor : {x_unsqueezed}")
print(f"New Tensor Shape : {x_unsqueezed.shape}")


Previous Target : tensor([0.2916, 0.1722, 0.9716, 0.7282, 0.4054, 0.7865, 0.9859, 0.6173, 0.5845])
Previous Shape : torch.Size([9])

New Tensor : tensor([[0.2916, 0.1722, 0.9716, 0.7282, 0.4054, 0.7865, 0.9859, 0.6173, 0.5845]])
New Tensor Shape : torch.Size([1, 9])

New Tensor : tensor([[0.2916],
        [0.1722],
        [0.9716],
        [0.7282],
        [0.4054],
        [0.7865],
        [0.9859],
        [0.6173],
        [0.5845]])
New Tensor Shape : torch.Size([9, 1])


In [194]:
# Torch.permute - rearange the target tensor [permute is also a view]
x_original = torch.rand(224, 224, 3) # (height, width, color_channels)

# Permute the original tensor [ rearage the dim order ]
x_permuted = x_original.permute(2, 0, 1)
print(f"\nPrevious Shape : {x_original.shape}")
print(f"New Shape      : {x_permuted.shape} ")  # [Color_channels, heigth, width]



Previous Shape : torch.Size([224, 224, 3])
New Shape      : torch.Size([3, 224, 224]) 


If you change one of tensors both of them will change because they are view

**permutated also a view**

In [195]:
x_original[0, 0, 0] = 22222
x_original[0, 0, 0]

tensor(22222.)

In [196]:
x_permuted[0, 0, 0]

tensor(22222.)

#Indexing ( selecting data from tensors )

In [197]:
# create a tensor
import torch
x = torch.arange(1 , 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [198]:
Y = torch.arange(1, 28).reshape(3, 3, 3)
Y

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [199]:
x.ndim

3

In [200]:
# index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [201]:
# index on middle bracket [ dim = 1 ]
x[0][0],x[0, 0] # both ways can use

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [202]:
#
x[0][0][0]

tensor(1)

In [203]:
#to get the 9 and 3,6,9
x[0, 2, 2],x[:,:,2]


(tensor(9), tensor([[3, 6, 9]]))

In [204]:
# select all from target dimention
x[:, 0]

tensor([[1, 2, 3]])

In [205]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [206]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [207]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [208]:
# get all values of 0 dim but only 1 index value of 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [209]:
x[0, 1, 1]

tensor(5)

In [210]:
x[0, 0, :]

tensor([1, 2, 3])

# PyTorch tensor & Numpy
PyTorch tensor -> NumPy-> torch.Tensor.numpy()

*   Pytorch.dtype = float 32
*     numpy.dtype = float 64




In [211]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# !Warning : when converting from numpy to pytorch, pytorch deflect numpy's dtype wich is float 64
#                            from pytorch to numpy, numpy deflect pytorch's dtype wich is float 32
array

array([1., 2., 3., 4., 5., 6., 7.])

In [212]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [213]:
tensor.dtype

torch.float64

In [214]:
# Change the value of the array
array = array + 5
array , tensor

(array([ 6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [215]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [216]:
# Chnage the tensor and see what happend to numpy_tensor
tensor = tensor + 5
tensor, numpy_tensor

(tensor([6., 6., 6., 6., 6., 6., 6.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducibility ( trying to take random out of random )

* In short how a neural network learns


To reduce the randomness in comes to the concept of a **random seed**

random seed flaver the randomness

In [217]:
torch.rand(3, 3) # psudo randomness [ genarated randomness ]

tensor([[0.0569, 0.4442, 0.7151],
        [0.8811, 0.1391, 0.8631],
        [0.3647, 0.0169, 0.0642]])

In [218]:
import torch

# 2 random tensors
rand_tensor_A = torch.rand(3, 4)
rand_tensor_B = torch.rand(3, 4)

print(rand_tensor_A)
print(rand_tensor_B)
print(rand_tensor_A == rand_tensor_B)

tensor([[0.0566, 0.6983, 0.2999, 0.9079],
        [0.8272, 0.3155, 0.6029, 0.5102],
        [0.8750, 0.6188, 0.7878, 0.5344]])
tensor([[0.7392, 0.4016, 0.2002, 0.1480],
        [0.2555, 0.4162, 0.5387, 0.2886],
        [0.8916, 0.2024, 0.4544, 0.9249]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [219]:
# Make some random but repreducible tensors
# Set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [220]:
# If someone else use the same code they get the same out put

#Check for GPU access with PyTorch


In [221]:
import torch
torch.cuda.is_available()

True

In [222]:
# Setup divice agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [223]:
# Count the number of divices
torch.cuda.device_count()

1

# Putting tensors (and models) on the gpu

In [224]:
# Create tensor (defult on cpu)
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [225]:
# move tensor to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# moving tensors back to the cpu


*   if the tensor is on GPU, can't tranform it to Numpy




In [228]:
transform_on_cpu = tensor_on_gpu.cpu().numpy()
transform_on_cpu

array([1, 2, 3])

In [229]:
tensor_on_gpu
## this is unchanged because we reasing to tranform_on_cpu


tensor([1, 2, 3], device='cuda:0')