<a href="https://colab.research.google.com/github/DinalAdithya/Learning-PYTorch/blob/main/Pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print (torch.__version__)

2.1.0+cu121


Intoduction to Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# no dimantions
scalar.ndim

0

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX =torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

In [ ]:
TENSOR[0][1][2]

tensor(6)

### Random TENSORS

1. These are importent becouse the way many neural networks learn with random Tensors.

2. Then adjust those random Tensors to better represnt data.

In [ ]:
# Create a random Tensors of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5645, 0.5390, 0.4492, 0.5870],
        [0.1884, 0.2565, 0.7888, 0.6916],
        [0.7950, 0.0431, 0.0749, 0.9769]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create random tensor with similar shape to an image tensor
ramdom_image_size_tensor = torch.rand(size= (3, 244, 244))
ramdom_image_size_tensor.shape, ramdom_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and ones


In [ ]:
# Creaate tensor with all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###Creating Range of Tensors and tensors like



In [ ]:
# use torch. range()[range dose not support so arange()]
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start = 1, end = 11)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(1,1000,77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
torch.arange(start = 1, end = 1000, step = 77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
# create tensors like (use this if need to create a tensor likes
# something else  ) it just copy the shape

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data type
***NOTE: 3 big errors

      1. Tensors not right dtypr
      2. Tensors not right shape
      3. Tensors not on the right device  


In [ ]:
# defult comes with float 32
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None)
tensor_type

tensor([3., 6., 9.])

In [ ]:
tensor_type.dtype

torch.float32

In [ ]:
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=torch.float16)
tensor_type.dtype

torch.float16

In [ ]:
# importent parameters to be aware of
tensor_type = torch.tensor([3.0, 6.0, 9.0],
                           dtype=None,# what data type is the tensor
                           device=None,# what devise is you tensor on
                           requires_grad=False)# whether or not track gradiants this tensors operations
tensor_type

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = tensor_type.type(torch.half) # or u can use (torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# even though we could multyply 2 tensors of defferent dtype here
# it not work on every places so be care full

float_16_tensor * tensor_type

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor *  float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor *  tensor_type

tensor([ 9., 36., 81.])

### Getting informations from tensors

1. Tensors not right dtypr     - tensor.dtype
2. Tensors not right shape         - tensor.shape
3. Tensors not on the right device - tensor.device

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6024, 0.5218, 0.5024, 0.1579],
        [0.9640, 0.2907, 0.7016, 0.8793],
        [0.5355, 0.5525, 0.3666, 0.9776]])

In [ ]:
# Find out details about tensors

print(some_tensor, "\n")
print(f"Datatype of tensor : {some_tensor.dtype}\n")

# these two are same acsept one is a attribute other one is def(function)
print(f"Shape of a tensor : {some_tensor.shape}")
print(f"Shape of a tensor : {some_tensor.size()}\n")

# all the tensor that we create is on cpu as defult
print(f"Device tensor is on : {some_tensor.device}")



tensor([[0.6024, 0.5218, 0.5024, 0.1579],
        [0.9640, 0.2907, 0.7016, 0.8793],
        [0.5355, 0.5525, 0.3666, 0.9776]]) 

Datatype of tensor : torch.float32

Shape of a tensor : torch.Size([3, 4])
Shape of a tensor : torch.Size([3, 4])

Device tensor is on : cpu


### Manipulating Tensors (tensor operations)


  

1.   Addition
2.   Subtraction
3.   Multiplication (elemnt-wise)
4.   Division
5.   Matrix multiplication




In [ ]:
# create a tensor & add 10 to it
gg = torch.tensor([1, 2, 3])

gg + 10

tensor([11, 12, 13])

In [ ]:
# PYTorch  in build function
gg.add(100)

tensor([101, 102, 103])

In [ ]:
# multiply tensor by 10
gg * 10


tensor([10, 20, 30])

In [ ]:
# Substract
gg - 10

tensor([-9, -8, -7])

In [ ]:
### matrix multiplication [2 types]
  # 1. Element-wise Multiplication
  # 2. matrix multiplication [dot products]

In [ ]:
# 1. Element-wise Multiplication
print(gg, "*", gg)
print(f"Equals:, {gg * gg}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:, tensor([1, 4, 9])


In [ ]:
# 2. matrix multiplication
%%time
torch.matmul(gg ,gg) # insted of matmul we can use mm [sorter virsion]

CPU times: user 160 µs, sys: 33 µs, total: 193 µs
Wall time: 320 µs


tensor(14)

In [ ]:
## or we can use @ to do the aboue same thing
%%time
gg @ gg
# time is way low for using @

CPU times: user 33 µs, sys: 7 µs, total: 40 µs
Wall time: 43.9 µs


tensor(14)

In [ ]:
#by hand = 1*1 + 2*2 + 3*3

In [ ]:
%%time
value = 0
for i in range(len(gg)):
  value += gg[i] * gg[i]
print(value)

tensor(14)
CPU times: user 836 µs, sys: 0 ns, total: 836 µs
Wall time: 843 µs


###                          **  Fun fact **
If we didnt print the [ print(value)] = 1.41ms


and use just value it take more time           = 6ms


same reason why c++ faster for gaming than python

In [ ]:
### One of the most common error = shap error

**1 . Inner dimentions must match**

*   (3, 2)  @  (3, 2) = Won't work
*   (2, 3)  @  (3, 2) = Will work
*   (3, 2)  @  (2, 3) = Will work

**2. The resulting matrix has the shape of the outer dimention**


1.   (2, 3)  @  (3, 2) -> (2, 2)
2.   (3, 2)  @  (2, 3) -> (3, 3)






## Error
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))


In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.4200, 0.4614],
        [0.3404, 0.2499]])

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.2105, 0.4763, 0.3376],
        [0.3526, 0.8042, 0.5619],
        [0.0274, 0.0324, 0.0602]])

In [ ]:
## Error
# shapes for metrix multiplication
tensor_A =  torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

## Error
torch.mm(tensor_A , tensor_B)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix shape issues, we can use **transpose**

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape ## now the shapes of thensor b is changed

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# now you dont get an error [becouse tensor_B is transpose now]
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes:      tensor_A = {tensor_A.shape}(same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplaing:                {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimention must match")
print("\noutput :")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes:      tensor_A = torch.Size([3, 2])(same as above), tensor_B.T = torch.Size([2, 3])
Multiplaing:                torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimention must match

output :
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Tensor Aggregation
#### Finding the min, mean, sum etc

In [ ]:
# Create a Tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# To Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
## Mean [ x.mean() dose not work ]  / torch.mean(x)
### becouse torch mean fun dose not work for dtype int64

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

# Finding the Positional mid and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.argmin() # return the index of the min value

tensor(0)

In [ ]:
x.argmax() # return the index of the max value

tensor(9)

#Reshaping, stacking, squeezing, and unsqueezing tensor
* reshaping - reshape an input tensor to a difine shape
* view - return view of an input tensor of certain shape but keep the same memory
* squeezing - removes all '1' dimensions from a tensor
* unsqueezing - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# let's create a tensor
import torch # note book can run the sell derectly from here
x = torch.arange(1., 11.)
x, x.shape, x.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 torch.float32)

In [ ]:
# Reshape = add extra dimention
x_reshape = x.reshape(2, 5) # this workd becouse 5*2= 10 [x has 10 element] any combinations oky
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# View = Change the view
z =  x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# changing z changes x
# because a view of a tensor shares the same memory as original input

z[ :, 0] = 5 # need to have a space before :
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0 ) # difoult dimention also 0
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim = 1 ) # can't have more than 1 dimention for this
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped = torch.rand(1, 9)
print(f"Tensor : {x_reshaped}")
print(f"Tensor Shape : {x_reshaped.shape}")

# removing extra dimentions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor : {x_squeezed}")
print(f"New Tensor Shape : {x_squeezed.shape}")


Tensor : tensor([[0.1679, 0.8803, 0.9835, 0.8975, 0.2034, 0.0436, 0.1066, 0.1250, 0.4149]])
Tensor Shape : torch.Size([1, 9])

New Tensor : tensor([0.1679, 0.8803, 0.9835, 0.8975, 0.2034, 0.0436, 0.1066, 0.1250, 0.4149])
New Tensor Shape : torch.Size([9])


In [ ]:
# Torch.unsqueezed() - adds a single dimension to a target tensor at a specific dim
print(f"Previous Target : {x_squeezed}")
print(f"Previous Shape : {x_squeezed.shape}")

# Add an extra dim with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim =  0)
print(f"\nNew Tensor : {x_unsqueezed}")
print(f"New Tensor Shape : {x_unsqueezed.shape}")


# dim 1
x_unsqueezed = x_squeezed.unsqueeze(dim =  1)
print(f"\nNew Tensor : {x_unsqueezed}")
print(f"New Tensor Shape : {x_unsqueezed.shape}")


Previous Target : tensor([0.1679, 0.8803, 0.9835, 0.8975, 0.2034, 0.0436, 0.1066, 0.1250, 0.4149])
Previous Shape : torch.Size([9])

New Tensor : tensor([[0.1679, 0.8803, 0.9835, 0.8975, 0.2034, 0.0436, 0.1066, 0.1250, 0.4149]])
New Tensor Shape : torch.Size([1, 9])

New Tensor : tensor([[0.1679],
        [0.8803],
        [0.9835],
        [0.8975],
        [0.2034],
        [0.0436],
        [0.1066],
        [0.1250],
        [0.4149]])
New Tensor Shape : torch.Size([9, 1])


In [ ]:
# Torch.permute - rearange the target tensor [permute is also a view]
x_original = torch.rand(224, 224, 3) # (height, width, color_channels)

# Permute the original tensor [ rearage the dim order ]
x_permuted = x_original.permute(2, 0, 1)
print(f"\nPrevious Shape : {x_original.shape}")
print(f"New Shape      : {x_permuted.shape} ")  # [Color_channels, heigth, width]



Previous Shape : torch.Size([224, 224, 3])
New Shape      : torch.Size([3, 224, 224]) 


If you change one of tensors both of them will change because they are view

**permutated also a view**

In [ ]:
x_original[0, 0, 0] = 22222
x_original[0, 0, 0]

tensor(22222.)

In [ ]:
x_permuted[0, 0, 0]

tensor(22222.)

#Indexing ( selecting data from tensors )

In [ ]:
# create a tensor
import torch
x = torch.arange(1 , 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
Y = torch.arange(1, 28).reshape(3, 3, 3)
Y

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [ ]:
x.ndim

3

In [ ]:
# index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index on middle bracket [ dim = 1 ]
x[0][0],x[0, 0] # both ways can use

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
#
x[0][0][0]

tensor(1)

In [ ]:
#to get the 9 and 3,6,9
x[0, 2, 2],x[:,:,2]


(tensor(9), tensor([[3, 6, 9]]))

In [ ]:
# select all from target dimention
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
# get all values of 0 dim but only 1 index value of 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 1, 1]

tensor(5)

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

# PyTorch tensor & Numpy
PyTorch tensor -> NumPy-> torch.Tensor.numpy()

*   Pytorch.dtype = float 32
*     numpy.dtype = float 64




In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# !Warning : when converting from numpy to pytorch, pytorch deflect numpy's dtype wich is float 64
#                            from pytorch to numpy, numpy deflect pytorch's dtype wich is float 32
array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# Change the value of the array
array = array + 5
array , tensor

(array([ 6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
# Chnage the tensor and see what happend to numpy_tensor
tensor = tensor + 5
tensor, numpy_tensor

(tensor([6., 6., 6., 6., 6., 6., 6.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducibility ( trying to take random out of random )

* In short how a neural network learns


To reduce the randomness in comes to the concept of a **random seed**

random seed flaver the randomness

In [ ]:
torch.rand(3, 3) # psudo randomness [ genarated randomness ]

tensor([[0.6279, 0.9989, 0.8325],
        [0.5520, 0.0217, 0.8776],
        [0.3752, 0.1405, 0.1523]])

In [ ]:
import torch

# 2 random tensors
rand_tensor_A = torch.rand(3, 4)
rand_tensor_B = torch.rand(3, 4)

print(rand_tensor_A)
print(rand_tensor_B)
print(rand_tensor_A == rand_tensor_B)

tensor([[0.3215, 0.9065, 0.0949, 0.9172],
        [0.8302, 0.3130, 0.7451, 0.9479],
        [0.5122, 0.4522, 0.8767, 0.8485]])
tensor([[0.9433, 0.3596, 0.6642, 0.5121],
        [0.6610, 0.9649, 0.2939, 0.3107],
        [0.7655, 0.3181, 0.6673, 0.6995]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Make some random but repreducible tensors
# Set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [ ]:
# If someone else use the same code they get the same out put

#Check for GPU access with PyTorch


In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup divice agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of divices
torch.cuda.device_count()

1

# Putting tensors (and models) on the gpu

In [ ]:
# Create tensor (defult on cpu)
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# moving tensors back to the cpu


*   if the tensor is on GPU, can't tranform it to Numpy




In [ ]:
transform_on_cpu = tensor_on_gpu.cpu().numpy()
transform_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu
## this is unchanged because we reasing to tranform_on_cpu


tensor([1, 2, 3], device='cuda:0')