<a href="https://colab.research.google.com/github/DinalAdithya/Learning-PYTorch/blob/main/PYTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.tensor([5, 3])
y = torch.tensor([2, 1])

print(x*y)

tensor([10,  3])


In [4]:
x = torch.zeros(2,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
x.shape

torch.Size([2, 4])

In [7]:
y = torch.rand([2, 5])
y

tensor([[0.9950, 0.4100, 0.7264, 0.4183, 0.9552],
        [0.5368, 0.8178, 0.0783, 0.9493, 0.7736]])